name: gendiff-tests

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run tests
        run: |
          make test
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 0790f7e4d2826dd6aac3cdf64da01e3624a4240d6d358a32112d2da69f4aa185
        with:
          coverageCommand: poetry run pytest --cov=gendiff --cov-report xml
